---
apiVersion: local.storage.openshift.io/v1
kind: LocalVolume
metadata:
  name: fec3-local-storage-dell03
  namespace: openshift-local-storage
spec:
  nodeSelector:
    nodeSelectorTerms:
    - matchExpressions:
        - key: ran.openshift.io/fec3-local-storage-dell03
          operator: Exists
  storageClassDevices:
    - storageClassName: "fec3-local-storage-dell03"
      volumeMode: Filesystem
      fsType: xfs
      # Update to match profile composition
      devicePaths:
        #- /dev/nvme1n1p4
        # - /dev/nvme1n2
