---
apiVersion: ran.openshift.io/v1
kind: PolicyGenTemplate
metadata:
  # The name will be used to generate the placementBinding and placementRule names as {name}-placementBinding and {name}-placementRule
  name: "flexranspr-group-hook"
  namespace: "ztp-group-cars2"
spec:
  bindingRules:
    # These policies will correspond to all clusters with this label:
    flexranspr-group-hook: ""
  mcp: "master"
  sourceFiles:
    - fileName: ConsoleOperatorDisable.yaml
      policyName: "config-policy"
    # Set ClusterLogForwarder & ClusterLogging as example might be better to create another policyTemp-Group
#    - fileName: ClusterLogForwarder.yaml
#      policyName: "config-policy"
#      spec:
#        outputs:
#          - type: "kafka"
#            name: kafka-open
#            # below url is an example
#            url: tcp://10.46.55.190:9092/test
#        pipelines:
#          - name: audit-logs
#            inputRefs:
#             - audit
#            outputRefs:
#             - kafka-open
#          - name: infrastructure-logs
#            inputRefs:
#             - infrastructure
#            outputRefs:
#             - kafka-open
#    - fileName: ClusterLogging.yaml # 30-Jan dcain testing logging delete
#      policyName: "config-policy"
#      spec:
#        curation:
#          curator:
#            schedule: "30 3 * * *"
#        collection:
#          logs:
#            type: "fluentd"
#            fluentd: {}
    - fileName: PtpConfigSlaveCvl.yaml   # Change to PtpConfigSlaveCvl.yaml for ColumbiaVille NIC
      policyName: "config-policy"
      metadata:
        name: "du-ptp-slave"
      spec:
        profile:
        - name: "slave"
          # This interface must match the hardware in this group
          interface: "ens2f0"
          ptp4lOpts: "-2 -s --summary_interval -4"
          phc2sysOpts: "-a -r -n 24"
    - fileName: StorageClass.yaml
      policyName: "config-policy"
      metadata:
        name: "lso-filesystemclass"
        annotations:
          storageclass.kubernetes.io/is-default-class: "true"
    - fileName: StorageClass.yaml
      policyName: "config-policy"
      metadata:
        name: "lso-blockclass"
    - fileName: StorageLV.yaml
      policyName: "config-policy"
      spec:
        storageClassDevices:
          - storageClassName: "lso-filesystemclass"
            volumeMode: Filesystem
            fsType: xfs
            devicePaths:
              - /dev/nvme0n1p5
          - storageClassName: "lso-blockclass"
            volumeMode: Block
            fsType: xfs
            devicePaths:
              - /dev/nvme0n1p6
    - fileName: DisableSnoNetworkDiag.yaml
      policyName: "config-policy"
    - fileName: PerformanceProfile.yaml
      policyName: "config-policy"
      spec:
        additionalKernelArgs:
          - crashkernel=512M
#          - rcupdate.rcu_normal_after_boot=0
          - rcupdate.rcu_normal_after_boot=1
          - intel_idle.max_cstate=0
          - module_blacklist=irdma
          - vfio_pci.enable_sriov=1
          - vfio_pci.disable_idle_d3=1
        cpu:
          # These must be tailored for the specific hardware platform
          isolated: "2-19,22-39"
          reserved: "0-1,20-21"
        hugepages:
          defaultHugepagesSize: 1G
          pages:
            - size: 1G
              count: 16
        workloadHints:
          realTime: true
          highPowerConsumption: false
          perPodPowerManagement: false
          #perPodPowerManagement: true
        net:
          userLevelNetworking: true
    - fileName: TunedPerformancePatch.yaml
      policyName: "config-policy"
      spec:
        profile:
          - name: performance-patch
            # The cmdline_crash CPU set must match the 'isolated' set in the PerformanceProfile above
            data: |
              [main]
              summary=Configuration changes profile inherited from performance created tuned
              include=openshift-node-performance-openshift-node-performance-profile
              [sysctl]
              kernel.timer_migration=1
              [scheduler]
              group.ice-ptp=0:f:10:*:ice-ptp.*
              group.ice-gnss=0:f:10:*:ice-gnss.*
              [service]
              service.stalld=start,enable
              service.chronyd=stop,disable
#              [sysfs]
#              /sys/devices/system/cpu/intel_pstate/max_perf_pct = 70
    - fileName: optional-extra-manifest/enable-crun-master.yaml
      policyName: "config-policy"
    - fileName: optional-extra-manifest/enable-crun-worker.yaml
      policyName: "config-policy"
#    --- sources needed for image registry (check ImageRegistry.md for more details)----
#    - fileName: StorageClass.yaml
#      policyName: "config-policy"
#      metadata:
#        name: image-registry-sc
#    - fileName: StoragePVC.yaml
#      policyName: "config-policy"
#      metadata:
#        name: image-registry-pvc
#        namespace: openshift-image-registry
#      spec:
#        accessModes:
#          - ReadWriteMany
#        resources:
#          requests:
#            storage: 100Gi
#        storageClassName: image-registry-sc
#        volumeMode: Filesystem
#    - fileName: ImageRegistryPV.yaml  # this is assuming that mount_point is set to `/var/imageregistry` in SiteConfig
                                       # using StorageClass `image-registry-sc` (see the first sc-file)
#      policyName: "config-policy"
#    - fileName: ImageRegistryConfig.yaml
#      policyName: "config-policy"
#      spec:
#        storage:
#          pvc:
#            claim: "image-registry-pvc"
#     ---- sources needed for image registry ends here ----
