---
apiVersion: ran.openshift.io/v1
kind: PolicyGenTemplate
metadata:
  # The name will be used to generate the placementBinding and placementRule names as {name}-placementBinding and {name}-placementRule
  name: "flexranicx-group-xr12"
  namespace: "ztp-group-cars2"
spec:
  bindingRules:
    # These policies will correspond to all clusters with this label:
    flexranicx-group-xr12: ""
  mcp: "master"
  sourceFiles:
    - fileName: ConsoleOperatorDisable.yaml
      policyName: "config-policy"
#    - fileName: ClusterLogForwarder.yaml
#      policyName: "config-policy"
#      spec:
#        outputs:
#          - name: loki-infra
#            secret:
#              name: remote-logging-secret
#            type: loki
#            # yamllint disable-line rule:line-length
#            url: https://logging-loki-openshift-logging.apps.shadowman.cars2.lab/api/logs/v1/infrastructure
#        pipelines:
#          - name: send-infra-logs
#            inputRefs:
#              - infrastructure
#            outputRefs:
#              - loki-infra
#            labels:
#              clustername: flexranicx
    - fileName: ClusterLogging.yaml
      policyName: "config-policy"
      spec:
        curation:
          curator:
            schedule: "30 3 * * *"
        collection:
          type: vector
    - fileName: PtpConfigSlaveCvl.yaml   # Change to PtpConfigSlaveCvl.yaml for ColumbiaVille NIC
      policyName: "config-policy"
      metadata:
        name: "du-ptp-slave"
      spec:
        profile:
        - name: "slave"
          # This interface must match the hardware in this group
          interface: "ens3f3"
          ptp4lOpts: "-2 -s --summary_interval -4"
          phc2sysOpts: "-a -r -n 24"
#    - fileName: StorageClass.yaml
#      policyName: "config-policy"
#      metadata:
#        name: "lso-filesystemclass"
#        annotations:
#          storageclass.kubernetes.io/is-default-class: "true"
#    - fileName: StorageClass.yaml
#      policyName: "config-policy"
#      metadata:
#        name: "lso-blockclass"
#    - fileName: StorageLV.yaml
#      policyName: "config-policy"
#      spec:
#        storageClassDevices:
#          - storageClassName: "lso-filesystemclass"
#            volumeMode: Filesystem
#            fsType: xfs
#            devicePaths:
#              - /dev/sda5
#          - storageClassName: "lso-blockclass"
#            volumeMode: Block
#            fsType: xfs
#            devicePaths:
#              - /dev/sda6
    - fileName: DisableSnoNetworkDiag.yaml
      policyName: "config-policy"
    - fileName: PerformanceProfile.yaml
      policyName: "config-policy"
      spec:
        cpu:
          # These must be tailored for the specific hardware platform
          isolated: "2-31,34-63"
          reserved: "0-1,32-33"
        hugepages:
          defaultHugepagesSize: 1G
          pages:
            - size: 1G
              count: 16
        workloadHints:
          realTime: true
          highPowerConsumption: false
          perPodPowerManagement: true
        net:
          userLevelNetworking: true
    - fileName: TunedPerformancePatch.yaml
      policyName: "config-policy"
      spec:
        profile:
          - name: performance-patch
            # The cmdline_crash CPU set must match the 'isolated' set in the PerformanceProfile above
            data: |
              [main]
              summary=Configuration changes profile inherited from performance created tuned
              include=openshift-node-performance-openshift-node-performance-profile
              [sysctl]
              kernel.timer_migration=1
              [scheduler]
              group.ice-ptp=0:f:10:*:ice-ptp.*
              group.ice-gnss=0:f:10:*:ice-gnss.*
              [service]
              service.stalld=start,enable
              service.chronyd=stop,disable
              [sysfs]
              /sys/devices/system/cpu/intel_pstate/max_perf_pct = 72
#    --- sources needed for image registry (check ImageRegistry.md for more details)----
#    - fileName: StorageClass.yaml
#      policyName: "config-policy"
#      metadata:
#        name: image-registry-sc
#    - fileName: StoragePVC.yaml
#      policyName: "config-policy"
#      metadata:
#        name: image-registry-pvc
#        namespace: openshift-image-registry
#      spec:
#        accessModes:
#          - ReadWriteMany
#        resources:
#          requests:
#            storage: 100Gi
#        storageClassName: image-registry-sc
#        volumeMode: Filesystem
#    - fileName: ImageRegistryPV.yaml  # this is assuming that mount_point is set to `/var/imageregistry` in SiteConfig
                                       # using StorageClass `image-registry-sc` (see the first sc-file)
#      policyName: "config-policy"
#    - fileName: ImageRegistryConfig.yaml
#      policyName: "config-policy"
#      spec:
#        storage:
#          pvc:
#            claim: "image-registry-pvc"
#     ---- sources needed for image registry ends here ----
