---
# yamllint disable
apiVersion: ran.openshift.io/v1
kind: PolicyGenTemplate
metadata:
  # The name will be used to generate the placementBinding and placementRule names as {name}-placementBinding and {name}-placementRule
  name: "group-dellxr8620t-vse5"
  namespace: "ztp-group-cars2"
spec:
  bindingRules:
    # These policies will correspond to all clusters with this label:
    group-dellxr8620t-vse5: ""
  mcp: "master"
  sourceFiles:
    - fileName: AcceleratorsNS.yaml
      policyName: "subscriptions-policy"
    - fileName: AcceleratorsOperGroup.yaml
      policyName: "subscriptions-policy"
    - fileName: AcceleratorsSubscription.yaml
      policyName: "subscriptions-policy"
    - fileName: ClusterLogging.yaml
      policyName: "config-policy"

    # The setting below overrides the default "worker" selector predefined in
    # the source-crs. The change is recommended on SNOs configured with PTP
    # event notification for forward compatibility with possible SNO expansion.
    # When the default setting is left intact, then in case of an SNO
    # expansion with one or more workers, PTP operator
    # would not create linuxptp-daemon containers on the worker node(s). Any
    # attempt to change the daemonsetNodeSelector will result in ptp daemon
    # restart and time synchronization loss.
    # After complying with the policy, complianceType can be set to a safer "musthave"
    # - fileName: PtpOperatorConfigForEvent.yaml
    #   policyName: "config-policy"
    #   complianceType: mustonlyhave
    #   spec:
    #     daemonNodeSelector:
    #       node-role.kubernetes.io/worker: ""
    #     ptpEventConfig:
    #       storageType: "storage-class-http-events"
    - fileName: PtpConfigSlaveCvl.yaml
      policyName: "config-policy"
      metadata:
        name: "du-ptp-slave"
      spec:
        profile:
        - name: "slave"
          # This interface must match the hardware in this group
          interface: "ens2f0"
          ptp4lOpts: "-2 -s --summary_interval -4"
          phc2sysOpts: "-a -r -n 24"
    - fileName: SriovOperatorConfig.yaml
      policyName: "config-policy"
      # For existing clusters with node selector set as "master",
      # change the complianceType to "mustonlyhave".
      # After complying with the policy, the complianceType can
      # be reverted to "musthave"
      complianceType: musthave
      spec:
        configDaemonNodeSelector:
          node-role.kubernetes.io/worker: ""
    - fileName: SriovFecClusterConfig.yaml
      policyName: "fec-policy"
      spec:
        drainSkip: true
        acceleratorSelector:
          pciAddress: 0000:f7:00.0
        physicalFunction:
         bbDevConfig:
          acc200:
            # Programming mode: 0 = VF Programming, 1 = PF Programming
            pfMode: false
            numVfBundles: 16
            maxQueueSize: 1024
            uplink4G:
              numQueueGroups: 0
              numAqsPerGroups: 16
              aqDepthLog2: 4
            downlink4G:
              numQueueGroups: 0
              numAqsPerGroups: 16
              aqDepthLog2: 4
            uplink5G:
              numQueueGroups: 4
              numAqsPerGroups: 16
              aqDepthLog2: 4
            downlink5G:
              numQueueGroups: 4
              numAqsPerGroups: 16
              aqDepthLog2: 4
            qfft:
              aqDepthLog2: 4
              numAqsPerGroups: 16
              numQueueGroups: 4
    - fileName: SriovNetworkNodePolicy.yaml
      remediationAction: enforce
      policyName: "sriov-vfio-policy-ens2f0"
      metadata:
        name: "sriov-nnp-vfio-ens2f0"
      spec:
        deviceType: vfio-pci
        mtu: 9216
        isRdma: false
        nicSelector:
          vendor: "8086"
          deviceID: "1593"
          pfNames: ["ens2f0#0-3"]
        numVfs: 8
        priority: 10
        resourceName: pci_sriov_net_ens2f0_0
    - fileName: SriovNetworkNodePolicy.yaml
      policyName: "sriov-netd-policy-ens2f0"
      remediationAction: enforce
      metadata:
        name: "sriov-nnp-netd-ens2f0"
      spec:
        deviceType: netdevice
        mtu: 9216
        isRdma: false
        nicSelector:
          vendor: "8086"
          deviceID: "1593"
          pfNames: ["ens2f0#4-7"]
        numVfs: 8
        priority: 10
        resourceName: pci_sriov_net_ens2f0_1
    - fileName: SriovNetwork.yaml
      policyName: "sriov-network-policy-mp"
      metadata:
        name: "sriov-nw-vran-mp1"
      spec:
        resourceName: pci_sriov_net_ens2f0_1
        networkNamespace: flexranl1
        vlan: 3812
        ipam: |-
          {"type": "static"}
        linkState: auto
    - fileName: SriovNetwork.yaml
      policyName: "sriov-network-policy-sp"
      metadata:
        name: "sriov-nw-vran-splane1"
      spec:
        resourceName: pci_sriov_net_ens2f0_1
        networkNamespace: flexranl1
        vlan: 400
        ipam: |-
          {"type": "static"}
        linkState: auto
    - fileName: SriovNetwork.yaml
      policyName: "sriov-network-policy-fh"
      metadata:
        name: "sriov-nw-vran-fh1"
      spec:
        resourceName: pci_sriov_net_ens2f0_0
        networkNamespace: flexranl1
        vlan: 3811
        ipam: |-
          {"type": "static"}
        linkState: auto
#    - fileName: StorageLV.yaml
#      policyName: "config-policy"
#      spec:
#        storageClassDevices:
#        - storageClassName: "example-storage-class-1"
#          volumeMode: Filesystem
#          fsType: xfs
#          devicePaths:
#          - /dev/sdb1
#        - storageClassName: "example-storage-class-2"
#          volumeMode: Filesystem
#          fsType: xfs
#          devicePaths:
#          - /dev/sdb2
        # This is required if PTP and BMER operators use HTTP transport.
        # The disk labels are created by ignitionConfigOverride in siteConfig.
        # - storageClassName: "storage-class-http-events"
        #   volumeMode: Filesystem
        #   fsType: xfs
        #   devicePaths:
        #   - /dev/disk/by-partlabel/httpevent1
        #   - /dev/disk/by-partlabel/httpevent2
    - fileName: DisableSnoNetworkDiag.yaml
      policyName: "config-policy"
    - fileName: PerformanceProfile.yaml
      policyName: "config-policy"
      spec:
        cpu:
          # These must be tailored for the specific hardware platform
          isolated: "2-31,34-63"
          reserved: "0-1,32-33"
        hugepages:
          defaultHugepagesSize: 1G
          pages:
            - size: 1G
              count: 32
        workloadHints:
          realTime: true
          highPowerConsumption: false
          perPodPowerManagement: true
    - fileName: TunedPerformancePatch.yaml
      policyName: "config-policy"
      spec:
        profile:
          - name: performance-patch
            data: |
              [main]
              summary=Configuration changes profile inherited from performance created tuned
              include=openshift-node-performance-openshift-node-performance-profile
              [sysctl]
              kernel.timer_migration=1
              [scheduler]
              group.ice-ptp=0:f:10:*:ice-ptp.*
              group.ice-gnss=0:f:10:*:ice-gnss.*
              [service]
              service.stalld=start,enable
              service.chronyd=stop,disable
              [sysfs]
              /sys/devices/system/cpu/intel_pstate/max_perf_pct = 70
    # # AmqInstance is required if PTP and BMER operators use AMQP transport
    # - fileName: AmqInstance.yaml
    #   policyName: "config-events-policy"
    #   annotations:
    #     ran.openshift.io/ztp-deploy-wave: "10"
    # - fileName: HardwareEvent.yaml
    #   policyName: "config-events-policy"
    #   spec:
    #     nodeSelector: {}
    #     transportHost: "amqp://amq-router.amq-router.svc.cluster.local"
    #     # transportHost: "http://hw-event-publisher-service.openshift-bare-metal-events.svc.cluster.local:9043"
    #     # storageType: "storage-class-http-events"
    #     logLevel: "debug"
    #
    # These CRs are to enable crun on master and worker nodes for 4.13+ only
    #
    # Include these CRs in the group PGT instead of the common PGT to make sure
    # they are applied after the operators have been successfully installed,
    # however, it's strongly recommended to include these CRs as day-0 extra manifests
    # to avoid the risk of an extra reboot.
    - fileName: optional-extra-manifest/enable-crun-master.yaml
      policyName: "config-policy"
    - fileName: optional-extra-manifest/enable-crun-worker.yaml
      policyName: "config-policy"
#    --- sources needed for image registry (check ImageRegistry.md for more details)----
#    - fileName: StorageClass.yaml
#      policyName: "config-policy"
#      metadata:
#        name: image-registry-sc
#    - fileName: StoragePVC.yaml
#      policyName: "config-policy"
#      metadata:
#        name: image-registry-pvc
#        namespace: openshift-image-registry
#      spec:
#        accessModes:
#          - ReadWriteMany
#        resources:
#          requests:
#            storage: 100Gi
#        storageClassName: image-registry-sc
#        volumeMode: Filesystem
#    - fileName: ImageRegistryPV.yaml  # this is assuming that mount_point is set to `/var/imageregistry` in SiteConfig
                                       # using StorageClass `image-registry-sc` (see the first sc-file)
#      policyName: "config-policy"
#    - fileName: ImageRegistryConfig.yaml
#      policyName: "config-policy"
#      spec:
#        storage:
#          pvc:
#            claim: "image-registry-pvc"
#     ---- sources needed for image registry ends here ----

#    --- sources needed for updating CRI-O workload-partitioning ----
#      more info here: on the base64 content https://docs.openshift.com/container-platform/4.11/scalability_and_performance/sno-du-enabling-workload-partitioning-on-single-node-openshift.html
#    - fileName: MachineConfigGeneric.yaml
#      policyName: "config-policy"
#      complianceType: mustonlyhave # This is to update array entry as opposed to appending a new entry.
#      metadata:
#        name: 02-master-workload-partitioning
#      spec:
#        config:
#          storage:
#            files:
#              - contents:
#                  # crio cpuset config goes below. This value needs to updated and matched PerformanceProfile. Check the link for more info on the content.
#                  source: data:text/plain;charset=utf-8;base64,W2NyaW8ucnVudGltZS53b3JrbG9hZHMubWFuYWdlbWVudF0KYWN0aXZhdGlvbl9hbm5vdGF0aW9uID0gInRhcmdldC53b3JrbG9hZC5vcGVuc2hpZnQuaW8vbWFuYWdlbWVudCIKYW5ub3RhdGlvbl9wcmVmaXggPSAicmVzb3VyY2VzLndvcmtsb2FkLm9wZW5zaGlmdC5pbyIKcmVzb3VyY2VzID0geyAiY3B1c2hhcmVzIiA9IDAsICJjcHVzZXQiID0gIjAtMSwyLTMiIH0=
#                mode: 420
#                overwrite: true
#                path: /etc/crio/crio.conf.d/01-workload-partitioning
#                user:
#                  name: root
#              - contents:
#                  # openshift cpuset config goes below. This value needs to be updated and matched with crio cpuset (array entry above this). Check the link for more info on the content.
#                  source: data:text/plain;charset=utf-8;base64,ewogICJtYW5hZ2VtZW50IjogewogICAgImNwdXNldCI6ICIwLTEsNTItNTMiCiAgfQp9Cg==
#                mode: 420
#                overwrite: true
#                path: /etc/kubernetes/openshift-workload-pinning
#                user:
#                  name: root
#     ---- sources needed for updating CRI-O workload-partitioning ends here ----
# yamllint enable
