---
apiVersion: ran.openshift.io/v1
kind: PolicyGenTemplate
metadata:
  # The name will be used to generate the placementBinding and placementRule names as {name}-placementBinding and {name}-placementRule
  name: "flexranspr-group-hook"
  namespace: "ztp-group-cars2"
spec:
  bindingRules:
    # These policies will correspond to all clusters with this label:
    flexranspr-group-hook: ""
  mcp: "master"
  sourceFiles:
    - fileName: ConsoleOperatorDisable.yaml
      policyName: "config-policy"
    # Set ClusterLogForwarder & ClusterLogging as example might be better to create another policyTemp-Group
#    - fileName: ClusterLogForwarder.yaml
#      policyName: "config-policy"
#      spec:
#        outputs:
#          - type: "kafka"
#            name: kafka-open
#            # below url is an example
#            url: tcp://10.46.55.190:9092/test
#        pipelines:
#          - name: audit-logs
#            inputRefs:
#             - audit
#            outputRefs:
#             - kafka-open
#          - name: infrastructure-logs
#            inputRefs:
#             - infrastructure
#            outputRefs:
#             - kafka-open
#    - fileName: ClusterLogging.yaml # 30-Jan dcain testing logging delete
#      policyName: "config-policy"
#      spec:
#        curation:
#          curator:
#            schedule: "30 3 * * *"
#        collection:
#          logs:
#            type: "fluentd"
#            fluentd: {}
# Logan Beach CARD
    - fileName: PtpConfigGmWpc.yaml
      policyName: "config-policy"
      spec:
        profile:
        - name: "grandmaster"
          phc2sysOpts: -r -u 0 -m -O -37 -N 8 -R 16 -s ens1f0 -n 24
          ptp4lConf: |
            [ens1f0]
            masterOnly 1
            [global]
            #
            # Default Data Set
            #
            twoStepFlag 1
            slaveOnly 0
            priority1 128
            priority2 128
            domainNumber 24
            #utc_offset 37
            clockClass 248
            clockAccuracy 0xFE
            offsetScaledLogVariance 0xFFFF
            free_running 0
            freq_est_interval 1
            dscp_event 0
            dscp_general 0
            #dataset_comparison ieee1588
            dataset_comparison G.8275.x
            G.8275.defaultDS.localPriority 128
            #
            # Port Data Set
            #
            logAnnounceInterval -3
            logSyncInterval -4
            logMinDelayReqInterval -4
            logMinPdelayReqInterval -4
            announceReceiptTimeout 3
            syncReceiptTimeout 0
            delayAsymmetry 0
            fault_reset_interval 4
            neighborPropDelayThresh 20000000
            masterOnly 1
            G.8275.portDS.localPriority 128
            #
            # Run time options
            #
            assume_two_step 0
            logging_level 6
            path_trace_enabled 0
            follow_up_info 0
            hybrid_e2e 0
            inhibit_multicast_service 0
            net_sync_monitor 0
            tc_spanning_tree 0
            tx_timestamp_timeout 50
            unicast_listen 0
            unicast_master_table 0
            unicast_req_duration 3600
            use_syslog 1
            verbose 1
            summary_interval 0
            kernel_leap 1
            check_fup_sync 0
            #
            # Servo Options
            #
            pi_proportional_const 0.0
            pi_integral_const 0.0
            pi_proportional_scale 0.0
            pi_proportional_exponent -0.3
            pi_proportional_norm_max 0.7
            pi_integral_scale 0.0
            pi_integral_exponent 0.4
            pi_integral_norm_max 0.3
            step_threshold 0.0
            first_step_threshold 0.00002
            max_frequency 900000000
            #clock_servo pi
            clock_servo linreg
            sanity_freq_limit 200000000
            ntpshm_segment 0
            #
            # Transport options
            #
            transportSpecific 0x0
            ptp_dst_mac 01:1B:19:00:00:00
            p2p_dst_mac 01:80:C2:00:00:0E
            udp_ttl 1
            udp6_scope 0x0E
            uds_address /var/run/ptp4l
            #
            # Default interface options
            #
            clock_type OC
            network_transport L2
            delay_mechanism E2E
            time_stamping hardware
            tsproc_mode filter
            delay_filter moving_median
            delay_filter_length 10
            egressLatency 0
            ingressLatency 0
            boundary_clock_jbod 0
            #
            # Clock description
            #
            productDescription ;;
            revisionData ;;
            manufacturerIdentity 00:00:00
            userDescription ;
            timeSource 0xA0
          ptpSettings:
            logReduce: "false"
          ts2phcConf: |
            [nmea]
            ts2phc.master 1
            [global]
            use_syslog  0
            verbose 1
            logging_level 7
            ts2phc.pulsewidth 100000000
            #GNSS module s /dev/ttyGNSS* -al use _0
            #cat /dev/ttyGNSS_1700_0 to find available serial port
            #example value of gnss_serialport is /dev/ttyGNSS_1700_0
            ts2phc.nmea_serialport /dev/gnss0
            leapfile  /usr/share/zoneinfo/leap-seconds.list
            [ens1f0]
            ts2phc.extts_polarity rising
            ts2phc.extts_correction 0
          ts2phcOpts: "-m"
#    - fileName: PtpConfigSlaveCvl.yaml   # Change to PtpConfigSlaveCvl.yaml for ColumbiaVille NIC
#      policyName: "config-policy"
#      metadata:
#        name: "du-ptp-slave"
#      spec:
#        profile:
#        - name: "slave"
#          # This interface must match the hardware in this group
#          interface: "ens1f0"
#          ptp4lOpts: "-2 -s --summary_interval -4"
#          phc2sysOpts: "-a -r -n 24"
#    - fileName: StorageClass.yaml
#      policyName: "config-policy"
#      metadata:
#        name: "lso-filesystemclass"
#        annotations:
#          storageclass.kubernetes.io/is-default-class: "true"
#    - fileName: StorageClass.yaml
#      policyName: "config-policy"
#      metadata:
#        name: "lso-blockclass"
#    - fileName: StorageLV.yaml
#      policyName: "config-policy"
#      spec:
#        storageClassDevices:
#          - storageClassName: "lso-filesystemclass"
#            volumeMode: Filesystem
#            fsType: xfs
#            devicePaths:
#              - /dev/nvme0n1p5
#          - storageClassName: "lso-blockclass"
#            volumeMode: Block
#            fsType: xfs
#            devicePaths:
#              - /dev/nvme0n1p6
    - fileName: DisableSnoNetworkDiag.yaml
      policyName: "config-policy"
    - fileName: PerformanceProfile.yaml
      policyName: "config-policy"
      spec:
        cpu:
          # These must be tailored for the specific hardware platform
          isolated: "2-31,34-63"
          reserved: "0-1,32-33"
        hugepages:
          defaultHugepagesSize: 1G
          pages:
            - size: 1G
              count: 32
        workloadHints:
          realTime: false
          highPowerConsumption: false
          perPodPowerManagement: true
    - fileName: TunedPerformancePatch.yaml
      policyName: "config-policy"
      spec:
        profile:
          - name: performance-patch
            # The cmdline_crash CPU set must match the 'isolated' set in the PerformanceProfile above
            data: |
              [main]
              summary=Configuration changes profile inherited from performance created tuned
              include=openshift-node-performance-openshift-node-performance-profile
              [sysctl]
              kernel.timer_migration=1
              [scheduler]
              group.ice-ptp=0:f:10:*:ice-ptp.*
              group.ice-gnss=0:f:10:*:ice-gnss.*
              [service]
              service.stalld=start,enable
              service.chronyd=stop,disable
              [sysfs]
              /sys/devices/system/cpu/intel_pstate/max_perf_pct = 70
#    - fileName: optional-extra-manifest/enable-crun-master.yaml
#      policyName: "config-policy"
#    - fileName: optional-extra-manifest/enable-crun-worker.yaml
#      policyName: "config-policy"
#    --- sources needed for image registry (check ImageRegistry.md for more details)----
#    - fileName: StorageClass.yaml
#      policyName: "config-policy"
#      metadata:
#        name: image-registry-sc
#    - fileName: StoragePVC.yaml
#      policyName: "config-policy"
#      metadata:
#        name: image-registry-pvc
#        namespace: openshift-image-registry
#      spec:
#        accessModes:
#          - ReadWriteMany
#        resources:
#          requests:
#            storage: 100Gi
#        storageClassName: image-registry-sc
#        volumeMode: Filesystem
#    - fileName: ImageRegistryPV.yaml  # this is assuming that mount_point is set to `/var/imageregistry` in SiteConfig
                                       # using StorageClass `image-registry-sc` (see the first sc-file)
#      policyName: "config-policy"
#    - fileName: ImageRegistryConfig.yaml
#      policyName: "config-policy"
#      spec:
#        storage:
#          pvc:
#            claim: "image-registry-pvc"
#     ---- sources needed for image registry ends here ----
