# Validate CPU topology
# $ for file in /sys/devices/system/cpu/cpu[0-9]*/topology/thread_siblings_list; do echo -n "$file "; cat $file; done |sort -k2 -n
# Supermicro with 1x Intel Ice Lake 6338R
---
apiVersion: performance.openshift.io/v2
kind: PerformanceProfile
metadata:
  name: ran-du-ldc1-smci04-profile0
spec:
  additionalKernelArgs:
  - rcupdate.rcu_normal_after_boot=0
  - crashkernel=512M
  #- nohz_full=4-31,36-63 
  #- kernel.timer_migration=1
  - slub_debug=FZPU
  - ignore_loglevel
  - initcall_debug
  cpu:
    isolated: 4-31,36-63
    reserved: 0-3,32-35
  net:
    userLevelNetworking: true
    devices:
    # intel I350
    - interfaceName: eno*
    # intel X550
    - interfaceName: enp25s0*
    # silicom sts  
    - interfaceName: enp81*
    - interfaceName: enp83*
  hugepages:
    defaultHugepagesSize: "1G"
    pages:
    - size: "1G"
      count: 16
      node: 0
  numa:
    topologyPolicy: best-effort
  realTimeKernel:
    enabled: true
  nodeSelector:
    node-role.kubernetes.io/ran-du-ldc1-smci04: ""
