---
apiVersion: v1
kind: Node
metadata:
  name: du4-ldc1
  labels:
    node-role.kubernetes.io/ran-du-ldc1-smci04: ""
    ran.openshift.io/ldc1-sriov-netdevice-smci04: ""
    ran.openshift.io/ldc1-sriov-netdevice-fh-smci04: ""
    ran.openshift.io/ldc1-sriov-vfio-smci04: ""
    #ran.openshift.io/ldc1-ptp-smci04: ""
    ran.openshift.io/acc100: ""
    #ran.openshift.io/ptp: ""
    ran.openshift.io/sriov: ""
    #ran.openshift.io/ldc1-local-storage-smci04: ""
    sts.silicom.com/config: "gm-1"
