apiVersion: nfd.openshift.io/v1
kind: NodeFeatureDiscovery
metadata:
  name: nfd-sts-silicom
  namespace: openshift-operators
spec:
  customConfig:
    configData: ""
  instance: ""
  operand:
    namespace: openshift-operators
  workerConfig:
    configData: |
      sources:
        pci:
          deviceClassWhitelist:
          - "0200"
          - "1200"
          deviceLabelFields:
          - "class"
          - "vendor"
          - "device"
          - "subsystem_vendor"
          - "subsystem_device"
        usb:
          deviceClassWhitelist:
          - "0e"
          - "ef"
          - "fe"
          - "ff"
          deviceLabelFields:
          - "class"
          - "vendor"
          - "device"
        custom:
        - name: "silicom.sts.devices"
          matchOn:
            - usbId:
                vendor: ["1374"]
                device: ["0001"]
            - pciId :
                vendor: ["8086"]
                device: ["1591"]
                subsystem_vendor: ["1374"]
                subsystem_device: ["02d8"]
                subsystem_device: ["02d0"]
                subsystem_device: ["02de"]
        - name: "intel.e810_c.devices"
          matchOn:
            - pciId :
                vendor: ["8086"]
                device: ["1591"]
        - name: "ublox.usb.serial"
          matchOn:
            - usbId:
                vendor: ["1546"]
                device: ["01a9"]
