---
###############################################################################
# SR-IOV Network Definition for the NS of the workload
# vran-mgmt + vlan 805 + vran_netdevice
###############################################################################
# NS = workload-4g-du-fec3
apiVersion: sriovnetwork.openshift.io/v1
kind: SriovNetwork
metadata:
  name: fec3-vran-mgmt
  namespace: openshift-sriov-network-operator
spec:
  resourceName: vran_netdevice
  networkNamespace: workload-4g-du-fec3
  vlan: 818
  ipam: |-
    {"type": "static"}
  linkState: auto
  # spoofChk: "<spoof_check>"
  # maxTxRate: <max_tx_rate>
  # minTxRate: <min_rx_rate>
  # vlanQoS: <vlan_qos>
  # trust: "<trust_vf>"
  # capabilities: <capabilities>
