---
apiVersion: sriovfec.intel.com/v2
kind: SriovFecClusterConfig
metadata:
  name: config-ran-du-fec3-dell03
  namespace: vran-acceleration-operators
spec:
    nodeSelector:
      ran.openshift.io/acc100: ""
      node-role.kubernetes.io/ran-du-fec3-dell03: ""
    acceleratorSelector: { pciAddress: 0000:c3:00.0 }
    physicalFunction:
      pfDriver: pci-pf-stub
      vfDriver: vfio-pci
      vfAmount: 5
      bbDevConfig:
        acc100:
          # Programming mode: 0 = VF Programming, 1 = PF Programming
          pfMode: false
          numVfBundles: 5
          maxQueueSize: 1024
          uplink4G:
            numQueueGroups: 4
            numAqsPerGroups: 16
            aqDepthLog2: 5
          downlink4G:
            numQueueGroups: 4
            numAqsPerGroups: 16
            aqDepthLog2: 5
          uplink5G:
            numQueueGroups: 0
            numAqsPerGroups: 16
            aqDepthLog2: 4
          downlink5G:
            numQueueGroups: 0
            numAqsPerGroups: 16
            aqDepthLog2: 4
