apiVersion: ran.openshift.io/v1alpha1
kind: ClusterGroupUpgrade
metadata:
  name: cgu-dave414
  namespace: ztp-common-cars2
spec:
  managedPolicies: 
    - common-du-prega414-config-policy
  enable: true
  clusters: 
  - flexranspr
  remediationStrategy:
    maxConcurrency: 2 
    timeout: 240
