#oc create secret generic assisted-deployment-pull-secret -n discrete --from-file=.dockerconfigjson=/home/dcain/pull-secret-fun/pull-secret-combined.json --type=kubernetes.io/dockerconfigjson
---
apiVersion: v1
kind: Secret
metadata:
  name: assisted-deployment-pull-secret
  namespace: discrete
stringData:
 .dockerconfigjson: ''