---
###############################################################################
# SR-IOV Network Definition for the NS of the workload
# vran-mp + vlan 2003 + vran_netdevice_fh
###############################################################################
# NS = workload-4g-du-ldc1
apiVersion: sriovnetwork.openshift.io/v1
kind: SriovNetwork
metadata:
  name: ldc1-dell00-vran-mp
  namespace: openshift-sriov-network-operator
spec:
  resourceName: vran_netdevice_fh
  networkNamespace: workload-4g-du-ldc1-dell00
  vlan: 2003
  ipam: |-
    {"type": "static"}
  linkState: auto
  # spoofChk: "<spoof_check>"
  # maxTxRate: <max_tx_rate>
  # minTxRate: <min_rx_rate>
  # vlanQoS: <vlan_qos>
  # trust: "<trust_vf>"
  # capabilities: <capabilities>
