---
###############################################################################
# SR-IOV Network Definition for the NS of the workload
# vran-bh-s1c-ng4t + vlan 3005 + vran_vfio
###############################################################################
# NS = workload-4g-cu-ldc1
apiVersion: sriovnetwork.openshift.io/v1
kind: SriovNetwork
metadata:
  name: ldc1-dell00-vran-bh-s1c-ng4t
  namespace: openshift-sriov-network-operator
spec:
  resourceName: vran_vfio
  networkNamespace: workload-4g-cu-ldc1-dell00
  vlan: 3005
  ipam: |-
    {}
  linkState: auto
  # spoofChk: "<spoof_check>"
  # maxTxRate: <max_tx_rate>
  # minTxRate: <min_rx_rate>
  # vlanQoS: <vlan_qos>
  # trust: "<trust_vf>"
  # capabilities: <capabilities>

