---
###############################################################################
# SR-IOV Network Definition for the NS of the workload
# vran-mgmt + vlan 814 + vran_vfio
###############################################################################
# NS = workload-4g-cu-ldc1-dell00
apiVersion: sriovnetwork.openshift.io/v1
kind: SriovNetwork
metadata:
  name: ldc1-dell00-vran-mgmt-a
  namespace: openshift-sriov-network-operator
spec:
  resourceName: vran_vfio
  networkNamespace: workload-4g-cu-ldc1-dell00
  vlan: 814
  ipam: |-
    {}
  linkState: auto
  # spoofChk: "<spoof_check>"
  # maxTxRate: <max_tx_rate>
  # minTxRate: <min_rx_rate>
  # vlanQoS: <vlan_qos>
  # trust: "<trust_vf>"
  # capabilities: <capabilities>
---
###############################################################################
# SR-IOV Network Definition for the NS of the workload
# vran-mgmt + vlan 814 + vran_netdevice
###############################################################################
# NS = workload-4g-cu-ldc1-dell00
apiVersion: sriovnetwork.openshift.io/v1
kind: SriovNetwork
metadata:
  name: ldc1-dell00-vran-mgmt-b
  namespace: openshift-sriov-network-operator
spec:
  resourceName: vran_netdevice
  networkNamespace: workload-4g-du-ldc1-dell00
  vlan: 814
  ipam: |-
    {"type": "static"}
  linkState: auto
  # spoofChk: "<spoof_check>"
  # maxTxRate: <max_tx_rate>
  # minTxRate: <min_rx_rate>
  # vlanQoS: <vlan_qos>
  # trust: "<trust_vf>"
  # capabilities: <capabilities>
