---
apiVersion: local.storage.openshift.io/v1
kind: LocalVolume
metadata:
  name: ldc1-local-storage-dell01
  namespace: openshift-local-storage
spec:
  nodeSelector:
    nodeSelectorTerms:
    - matchExpressions:
        - key: ran.openshift.io/ldc1-local-storage-dell01
          operator: Exists
  storageClassDevices:
    - storageClassName: "ldc1-local-storage-dell01"
      volumeMode: Filesystem
      fsType: xfs
      # Update to match profile composition
      devicePaths:
        #- /dev/nvme1n1p4
        # - /dev/nvme1n2
