# Example for a Dell DU: ran-du-fec3-dell03
---
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfigPool
metadata:
  name:  ran-du-fec3-dell03
  labels:
    machineconfiguration.openshift.io/role: ran-du-fec3-dell03
spec:
  machineConfigSelector:
    matchExpressions:
      - {
          key: machineconfiguration.openshift.io/role,
          operator: In,
          values: [worker, ran, ran-du-fec3-dell03]
        }
  paused: false
  nodeSelector:
    matchLabels:
      node-role.kubernetes.io/ran-du-fec3-dell03: ""
