# Validate CPU topology
# $ for file in /sys/devices/system/cpu/cpu[0-9]*/topology/thread_siblings_list; do echo -n "$file "; cat $file; done |sort -k2 -n
# Dell EMC with 1x Intel Ice Lake 6338R
---
apiVersion: performance.openshift.io/v2
kind: PerformanceProfile
metadata:
  name: ran-du-fec3-dell03-profile0
spec:
  additionalKernelArgs:
  - rcupdate.rcu_normal_after_boot=0
  - crashkernel=512M
  cpu:
    isolated: "4-31,36-63"
    reserved: "0-3,32-35"
  net:
    userLevelNetworking: true
    devices:
    # dell e810        
    - interfaceName: ens3f*
    - interfaceName: ens4f*
    # broadcom BCM57504 onboard        
    - interfaceName: eno8303np0
    - interfaceName: eno8403np1
    - interfaceName: eno8503np2
    - interfaceName: eno8603np3
  hugepages:
    defaultHugepagesSize: "1G"
    pages:
    - size: "1G"
      count: 16
      node: 0
  numa:
    topologyPolicy: best-effort
  realTimeKernel:
    enabled: false
  nodeSelector:
    node-role.kubernetes.io/ran-du-fec3-dell03: ""
