---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  # Each SITE_ID is a different zone
  topology.kubernetes.io/zone: fec3

resources:
  - 00-mcp-ran-du-fec3-dell03.yaml
  - 01-pao-ran-du-fec3-dell03-profile0.yaml
  #- 02-node-labels.yaml
  #- 03-node-labels.yaml
