---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: policies-carslab
  namespace: openshift-gitops
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: policies-sub
  project: policy-app-project
  source:
    path: site-policies
    repoURL: https://github.com/mgonzalezo/carslab-public
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
