---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ns.yaml
- common-policies/policy-acpipm.yaml
- common-policies/policy-kepler.yaml
- common-policies/policy-vseloki.yaml
- common-policies/policy-vseextras.yaml
- common-policies/policy-latencyrhel9.yaml

generators:
# This is common to all RAN DU deployments
- common-policies/common-ranGen.yaml
#- common-policies/common-ranGen-vse414.yaml
- common-policies/common-ranGen-prega414.yaml

# This group policy is for Dell EMC XR12 based deployments:
- group-policies/group-xr12-flexran2.yaml
- group-policies/group-xr12-flexranicx.yaml
# This group policy is for Supermicro X12 based deployments:
- group-policies/group-smcx12-vse2.yaml
# This group policy is for Dell XR8620t based deployments:
- group-policies/group-hook-flexranspr.yaml
# This group policy is for Dell R760 based deployments:
- group-policies/group-dellr760-vse3.yaml
# This group policy is for Dell R750 based deployments:
- group-policies/group-dellr750-vse4.yaml

# This group validator policy is for Dell EMC XR12 based deployments:
- group-policies/group-xr12-flexran2-validator.yaml
- group-policies/group-xr12-flexranicx-validator.yaml
# This group validator policy is for Supermicro X12 based deployments:
- group-policies/group-smcx12-vse2-validator.yaml
# This group validator policy is for Dell XR8620t based deployments:
- group-policies/group-hook-flexranspr-validator.yaml
# This group validator policy is for Dell R760 based deployments:
- group-policies/group-dellr760-vse3-validator.yaml
# This group validator policy is for Dell R750 based deployments:
- group-policies/group-dellr750-vse4-validator.yaml

# This group policy is for all compressed 3-node cluster deployments:
#- group-du-3node-ranGen.yaml
# This group validator policy is for all compressed 3-node cluster deployments:
#- group-du-3node-validator-ranGen.yaml
# This group policy is for all standard cluster deployments:
#- group-du-standard-ranGen.yaml
# This group validator policy is for all standard cluster deployments:
#- group-du-standard-validator-ranGen.yaml

# These are examples that should be replicated for every individual site:
#- site-specific-policies/flexran2-cars2-lab.yaml
#- site-specific-policies/flexranicx-cars2-lab.yaml
#- site-specific-policies/fiesta-cars2-lab.yaml
#- site-specific-policies/flexrankepler-cars2-lab.yaml
#- site-specific-policies/flexranspr-cars2-lab.yaml
#- example-multinode-site.yaml

# These are cluster specific policies:
- cluster-specific-policies/gnb-flexran2-cars2-lab.yaml
- cluster-specific-policies/gnb-flexranicx-cars2-lab.yaml
#- cluster-specific-policies/gnb-flexrankepler-cars2-lab.yaml
- cluster-specific-policies/gnb-flexranspr-cars2-lab.yaml
