apiVersion: sriovfec.intel.com/v2
kind: SriovFecClusterConfig
metadata:
  name: config
  namespace: vran-acceleration-operators
spec:
  acceleratorSelector:
    #pciAddress: 0000:8a:00.0
    pciAddress: 0000:51:00.0
  drainSkip: true
  nodeSelector:
    node-role.kubernetes.io/master: ""
  physicalFunction:
    bbDevConfig:
      acc100:
        downlink4G:
          aqDepthLog2: 4
          numAqsPerGroups: 16
          numQueueGroups: 0
        downlink5G:
          aqDepthLog2: 4
          numAqsPerGroups: 16
          numQueueGroups: 4
        maxQueueSize: 1024
        numVfBundles: 16
        pfMode: false
        uplink4G:
          aqDepthLog2: 4
          numAqsPerGroups: 16
          numQueueGroups: 0
        uplink5G:
          aqDepthLog2: 4
          numAqsPerGroups: 16
          numQueueGroups: 4
    pfDriver: vfio-pci
    vfAmount: 16
    vfDriver: vfio-pci
  priority: 1
