---
apiVersion: v1
items:
- apiVersion: operators.coreos.com/v1
  kind: OperatorGroup
  metadata:
    annotations:
      olm.providedAPIs: SriovFecClusterConfig.v2.sriovfec.intel.com,SriovFecNodeConfig.v2.sriovfec.intel.com
    name: vran-operators
    namespace: vran-acceleration-operators
  spec:
    targetNamespaces:
    - vran-acceleration-operators
    upgradeStrategy: Default
kind: List
metadata:
  resourceVersion: ""
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/sriov-fec.vran-acceleration-operators: ""
  name: sriov-fec-subscription
  namespace: vran-acceleration-operators
spec:
  channel: stable
  installPlanApproval: Manual
  name: sriov-fec
  source: vse-operators
  sourceNamespace: openshift-marketplace
  startingCSV: sriov-fec.v2.6.1
