#---
#apiVersion: operators.coreos.com/v1alpha1
#kind: CatalogSource
#metadata:
#  annotations:
#    target.workload.openshift.io/management: '{"effect": "PreferredDuringScheduling"}'
#  name: community414-operators
#  namespace: openshift-marketplace
#spec:
#  displayName: 4.14 Community Operators
#  image: registry.redhat.io/redhat/community-operator-index:v4.14
#  publisher: Red Hat
#  sourceType: grpc
#  updateStrategy:
#    registryPoll:
#      interval: 10m0s
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/kepler-operator.openshift-operators: ""
  name: kepler-operator
  namespace: openshift-operators
spec:
  channel: alpha
  installPlanApproval: Automatic
  name: kepler-operator
  #source: community414-operators
  source: community-operators
  sourceNamespace: openshift-marketplace
  startingCSV: kepler-operator.v0.6.2
---
apiVersion: kepler.system.sustainable.computing.io/v1alpha1
kind: Kepler
metadata:
  labels:
    app.kubernetes.io/instance: kepler
    app.kubernetes.io/name: kepler
    app.kubernetes.io/part-of: kepler-operator
  name: kepler
spec:
  exporter:
    port: 9103
