---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    openshift.io/cluster-monitoring: "true"
    openshift.io/user-monitoring: "true"
  name: flexranl1
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: system:openshift:scc:privileged
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:privileged
subjects:
- kind: ServiceAccount
  name: sa-flexran
  namespace: flexranl1
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
  name: sa-flexran
  namespace: flexranl1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flexran-binary-release
  namespace: flexranl1
  labels:
    app: flexran-binary-release
    name: flexran-binary-release
    node-role.kubernetes.io/master: ""
spec:
  selector:
    matchLabels:
      node-role.kubernetes.io/master: ""
  serviceName: flexran-binary-release
  replicas: 1
  strategy:
    type: Recreate
  template:
   metadata:
     labels:
       node-role.kubernetes.io/master: ""
     annotations:
       cpu-c-states.crio.io: "enable"
       cpu-freq-governor.crio.io: "performance"
       cpu-load-balancing.crio.io: "disable"
       cpu-quota.crio.io: "disable"
       irq-load-balancing.crio.io: "disable"
#       k8s.v1.cni.cncf.io/networks: |-
#         [
#           {
#             "name": "sriov-nw-mh",
#             "ips": ["10.27.6.30/27"]
#           },
#           {
#             "name": "sriov-nw-vran-mgmt",
#             "ips": ["10.27.5.30/27"]
#           }
#         ]
   spec:
     terminationGracePeriodSeconds: 20
     serviceAccountName: sa-flexran
     serviceAccount: sa-flexran
     runtimeClassName: performance-openshift-node-performance-profile
     nodeSelector:
       node-role.kubernetes.io/master: ""
     containers:
       - name: flexran-l1app
         #image: quay.io/redhat-partner-solutions/flexranl1:22.11a-sustainability-dynamic
         image: quay.io/redhat-partner-solutions/flexranl1:23.07-telcoqe
         imagePullPolicy: Always
         command: [ "/bin/bash", "-c", "--" ]
         args: ["sh docker_entry.sh -m timer ; top"]
         tty: true
         stdin: true
         volumeMounts:
           - name: hugepage
             mountPath: /hugepages
           - name: varrun
             mountPath: /var/run/dpdk
             readOnly: false
#           - name: tests
#             mountPath: /home/flexran/tests
#             readOnly: false
         resources:
           requests:
             memory: "64Gi"
#             openshift.io/pci_sriov_net_ens3f0_0: 1
#             openshift.io/pci_sriov_net_ens3f0_1: 1
             intel.com/intel_fec_acc100: '1'
             hugepages-1Gi: 16Gi
             cpu: "32"
           limits:
             memory: "64Gi"
#             openshift.io/pci_sriov_net_ens3f0_0: 1
#             openshift.io/pci_sriov_net_ens3f0_1: 1
             intel.com/intel_fec_acc100: '1'
             hugepages-1Gi: 16Gi
             cpu: "32"
         securityContext:
             privileged: false
             #runAsNonRoot: true
             runAsUser: 0
             capabilities:
               add:
                 - CAP_SYS_ADMIN # required by L1
# netdevice       - CAP_NET_ADMIN
                 - CAP_IPC_LOCK # required for hugepages L1 and L2
                 - CAP_SYS_NICE # required by L2
     volumes:
       - name: hugepage
         emptyDir:
           medium: HugePages
       - name: varrun
         emptyDir: {}
#       - name: tests
#         hostPath:
#           path: "/home/tmp_flexran/tests"
