# Example for a SMC DU: ran-du-ldc1-smci01
---
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfigPool
metadata:
  name:  ran-du-ldc1-smci01
  labels:
    machineconfiguration.openshift.io/role: ran-du-ldc1-smci01
spec:
  machineConfigSelector:
    matchExpressions:
      - {
          key: machineconfiguration.openshift.io/role,
          operator: In,
          values: [worker, ran, ran-du-ldc1-smci01]
        }
  paused: false
  nodeSelector:
    matchLabels:
      node-role.kubernetes.io/ran-du-ldc1-smci01: ""
