# Validate CPU topology
# $ for file in /sys/devices/system/cpu/cpu[0-9]*/topology/thread_siblings_list; do echo -n "$file "; cat $file; done |sort -k2 -n
# Supermicro with 1x Intel Ice Lake 6338R
---
apiVersion: performance.openshift.io/v2
kind: PerformanceProfile
metadata:
  name: ran-du-ldc1-smci01-profile0
spec:
  additionalKernelArgs:
  - rcupdate.rcu_normal_after_boot=0
  - crashkernel=512M
  #- nohz=off
  #- nohz_full=4-31,36-63 
  - slub_debug=FZPU
  cpu:
    isolated: 4-31,36-63
    reserved: 0-3,32-35
  net:
    userLevelNetworking: true
    devices:
    # intel I350
    - interfaceName: eno*
    # intel X550
    - interfaceName: enp25s0*
    # intel e810
    - interfaceName: enp138s0*
  globallyDisableIrqLoadBalancing: true
  hugepages:
    defaultHugepagesSize: 1G
    pages:
    - size: 1G
      count: 32
      node: 0
  numa:
    topologyPolicy: single-numa-node
  realTimeKernel:
    enabled: true
  nodeSelector:
    node-role.kubernetes.io/ran-du-ldc1-smci01: ""
