apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# ConfigMap generator for extra manifests
configMapGenerator:
  - name: extra-manifests
    namespace: du1-1-fiesta-cars2-lab
    files:
      - extra-manifests/01-container-mount-ns-and-kubelet-conf-master.yaml
      - extra-manifests/03-sctp-machine-config-master.yaml
      - extra-manifests/06-kdump-master.yaml
      - extra-manifests/07-sriov-related-kernel-args-master.yaml
      - extra-manifests/08-set-rcu-normal-master.yaml
      - extra-manifests/09-openshift-marketplace-ns.yaml
      - extra-manifests/99-crio-disable-wipe-master.yaml
      - extra-manifests/99-sync-time-once-master.yaml
      - extra-manifests/03-workload-partitioning.yaml

generatorOptions:
  disableNameSuffixHash: true

# Resources to deploy
resources:
  - ns.yaml
  - ns-fiesta.yaml
  - secrets.yaml
  - secrets-fiesta-ns.yaml
  - clusterinstance.yaml
