apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# ConfigMap generator for extra manifests
configMapGenerator:
  - name: extra-manifests
    namespace: fiesta
    files:
      - extra-manifests/master-core-password.yaml

generatorOptions:
  disableNameSuffixHash: true

# Resources to deploy
resources:
  - ns.yaml
  - secrets.yaml
  - clusterinstance.yaml
