#oc create secret generic assisted-deployment-pull-secret -n bronco --from-file=.dockerconfigjson=/home/dcain/pull-secret-fun/pull-secret-prega414-final.jsonn --type=kubernetes.io/dockerconfigjson
---
apiVersion: v1
kind: Secret
metadata:
  name: assisted-deployment-pull-secret
  namespace: bronco
stringData:
#  .dockerconfigjson: '{"auths":{"registry.cars2.lab:5000":{"auth":"BASE64","email":"username@redhat.com"}}}'
#stringData:
 .dockerconfigjson: ''
